### ISSUE TITLE
out of range error in line 60 mmascrape.py. Good job by the way getting the ball rolling this way!!

### ISSUE THREAD

**Issue by robinhood-me** [mapattacker/mmaStats#7]
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 "/Users/robinhood/aa-workspace-python/GMANE/MMA from MapAttacker/mmascrape.py"
number of fighters to scrape: 2  ### I tried lots of different numbers of fighters and got same error                message, I have noticed in the past that out of range error is when something else is going into
the field than what you think is, like it is not an integer or something (like a string instead).
Script completed in 0.08 min
Traceback (most recent call last):
  File "/Users/robinhood/aa-workspace-python/GMANE/MMA from MapAttacker/mmascrape.py", line 60, in <module>
    Win = winLost[0].getText()
IndexError: list index out of range   ### I put print winLost after line 59 and got [] , so the list is empty which is out of range because there is no data.

Process finished with exit code 0
Robin Hood
github account:https://github.com/robinhood-me/python_learning
btw, do you understand the gitignore file in my repository and what it is there for? I am new to github. I think it is great that you thought of sharing your code here and I got to try it and learn from it.

If you want to talk with me, my email is rhcrco@hotmail.com, or just start an issue on my gibhub and we can update the issue if we have a conversation.

I liked you Blog, you really seemed to be good at applying lots of different visualizations! did this required using the data differently, or pulling from different fields in the table?
I also had the idea that maybe you could make it easier for a person to add a UFC fighters name to the base url, like just ask the input to be the fighters name and append it to the sherdog url yourself. This was tedious when I was trying out your code. I had to fist past in the Sherdog url, and then paste in the full name of the fighter from the site itself (there seemed to be some code after the fighters name i think that only showed if I first went to the site and looked up a name. Just a thought.

**Comment by mapattacker** [comment]
Hi Robin,

You might letting me know which fighter's url you used for the start? From my experience after scraping a number of fighters, even if they have zero fights, they did put in 0 in the site. 

I didn't meant it such that one need to go to put in the sherdog domain name and fighters name as the url path. One just need to search for the fighter in their search box and it will give you the fighter's page. Then copy the whole fighter's url path out and paste it in the raw_input.

But, you are right too, It is possible to make an improvement in the starting url, I think one way is to use the package selenium to allow input of a fighter's name in the raw_input, and push it to the web search bar in sherdog.com fighter's query. Their search engine will then be able to intelligently find the closest match to a fighter with the url. Won't be doing that in this case though. :p

Thanks for the encouragement! There are still lots to learn and Dr Chuck did a good job in accelerating this process.

I think gitignore allows u to specify which are the files for github to ignore when making a commit. I'm only a few weeks old to github too, but getting the hand of it. Just try each function slow and steadily and u will get the hang of it eventually.
